/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tma02partaii;

import Orders.Order;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 *
 * @author cex
 */

public class Customer 
{

    
    private final String name;
    private final Map<Integer, Order> orders;
    
    public Customer(String name)
    {
        this.orders = new HashMap<>();
        this.name = name;
    }
    
    public String getName()
    {
        return name;
    }

    public void AddOrder(Order order) 
    {
        orders.put(order.getNumber(), order);
    }
    
    // Autogenerated
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Customer other = (Customer) obj;
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }
    
}