/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tma02partaii;

import java.util.Objects;

/**
 * Encapsulates a review including the actual textual review made
 */
public class Review {    

    private final String text;
    public Review(String text)
    {
        this.text = text;
    }
    
    public String getText()
    {
        return text;
    }
    
    // Autogenerated
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 61 * hash + Objects.hashCode(this.text);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Review other = (Review) obj;
        if (!Objects.equals(this.text, other.text)) {
            return false;
        }
        return true;
    }
}
