package Orders;

import java.util.Objects;
import tma02partaii.Product;

/**
 *
 * @author cex
 */
public class OrderItem
{    
    public OrderItem(Product product)
    {
        this.product = product;
    }
    
    public Product product;
    
    // AutoGenerated
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + Objects.hashCode(this.product);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OrderItem other = (OrderItem) obj;
        if (!Objects.equals(this.product, other.product)) {
            return false;
        }
        return true;
    }
}
